#pragma once
#include <wdm.h>

PDEVICE_OBJECT g_connDevice;
UNICODE_STRING dev, dos;

#define IO_START_MON CTL_CODE(FILE_DEVICE_UNKNOWN, 0x666, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_STOP_MON CTL_CODE(FILE_DEVICE_UNKNOWN, 0x667, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_GETDATA CTL_CODE(FILE_DEVICE_UNKNOWN, 0x668, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

NTSTATUS connDispatchPass(PDEVICE_OBJECT deviceObject, PIRP Irp);

NTSTATUS connCreateAttach(PDRIVER_OBJECT driverObject);

NTSTATUS connDeviceControl(PDEVICE_OBJECT deviceObject, PIRP Irp);

NTSTATUS connCloseCall(PDEVICE_OBJECT deviceObject, PIRP Irp);

NTSTATUS connCreateCall(PDEVICE_OBJECT deviceObject, PIRP Irp);
